import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:nura_wallet/core/security/key_derivation.dart';

/// The reference vectors, generated by running the shipping TypeScript implementation against the
/// exact libraries it bundles. They are the definition of "correct" for this port: matching them
/// means an existing user's vault opens, and failing to match means it does not.
Map<String, dynamic> _vectors() {
  final file = File('test/vectors/reference_vectors.json');

  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

String _hex(List<int> bytes) =>
    bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

void main() {
  final vectors = _vectors();

  group('Argon2id vault key', () {
    test('reproduces the TypeScript derivation byte for byte', () {
      final vault = vectors['vaultKdf'] as Map<String, dynamic>;
      final salt = Uint8List.fromList(
        base64Decode(vault['saltBase64'] as String),
      );

      final key = deriveVaultKey(vault['password'] as String, salt);

      expect(_hex(key), vault['keyHex']);
    });

    test('uses the cost the existing vaults were written under', () {
      final params =
          (vectors['vaultKdf'] as Map<String, dynamic>)['params']
              as Map<String, dynamic>;

      expect(Argon2Params.memorySizeKb, params['memorySize']);
      expect(Argon2Params.iterations, params['iterations']);
      expect(Argon2Params.parallelism, params['parallelism']);
      expect(Argon2Params.hashLength, params['hashLength']);
    });

    test('a different salt yields a different key', () {
      final other = Uint8List(16)..fillRange(0, 16, 0x99);

      expect(
        _hex(deriveVaultKey('correct horse battery staple', other)),
        isNot((vectors['vaultKdf'] as Map<String, dynamic>)['keyHex']),
      );
    });
  });

  group('unlock hash', () {
    final unlock = vectors['unlockHash'] as Map<String, dynamic>;

    test('salt matches the shipped constant', () {
      expect(unlockSalt, unlock['saltUtf8']);
    });

    // Includes a non-ASCII passphrase on purpose: the hash is taken over UTF-8 bytes, and a port that
    // encoded as Latin-1 or normalised the string would still pass an ASCII-only test.
    for (final entry in (unlock['cases'] as Map<String, dynamic>).entries) {
      final password = jsonDecode(entry.key) as String;

      test('matches for ${jsonEncode(password)}', () {
        expect(hashUnlockPassword(password), entry.value);
      });
    }

    test('refuses an empty passphrase rather than inventing a hash', () {
      expect(() => hashUnlockPassword(''), throwsArgumentError);
    });
  });
}
